# Generated by Django 3.2 on 2022-06-06 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_id', models.UUIDField(verbose_name=uuid.UUID('288267b3-75d1-4536-8180-e3a7374b628a'))),
            ],
        ),
    ]
