# Generated by Django 3.2 on 2022-06-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_from',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailtype',
            name='template',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
